# Generated by Django 4.1.7 on 2023-04-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menufood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'USER'), (1, 'STORE')], default=0),
        ),
    ]
