# Generated by Django 4.1.7 on 2023-03-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menufood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcribes',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcribes',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
