# Generated by Django 4.1.7 on 2023-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menufood', '0002_subcribes_active_subcribes_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verify',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
