# Generated by Django 4.1.7 on 2023-03-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menufood', '0002_orderdetail_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'store')},
            },
        ),
    ]
