# Generated by Django 4.1.7 on 2023-04-27 08:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menufood', '0002_alter_menuitem_store_alter_subcribes_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
