# Generated by Django 4.1.7 on 2023-04-27 08:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menufood', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, null=True, verbose_name='image'),
        ),
    ]
