# Generated by Django 4.1.7 on 2023-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menufood', '0003_alter_user_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_store',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
