# Generated by Django 4.1.7 on 2023-04-25 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menufood', '0006_alter_menuitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='store',
            field=models.ForeignKey(limit_choices_to={'user_role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcribes',
            name='follower',
            field=models.ForeignKey(limit_choices_to={'user_role': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcribes',
            name='store',
            field=models.ForeignKey(limit_choices_to={'user_role': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
    ]
